# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mkerl}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Lerner"]
  s.date = %q{2010-04-29}
  s.default_executable = %q{mkerl}
  s.description = %q{This includes tests, reloader, an application, supervisor and a boot file. It's pretty slick}
  s.email = %q{arilerner@mac.com}
  s.executables = ["mkerl"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/mkerl",
     "lib/mkerl.rb",
     "mkerl.gemspec",
     "templates/Emakefile",
     "templates/Makefile",
     "templates/README.markdown",
     "templates/app",
     "templates/basic_file.erl",
     "templates/basic_test.erl",
     "templates/gitignore",
     "templates/make_boot.erl",
     "templates/reloader.erl",
     "templates/start.sh",
     "templates/supervisor.erl",
     "templates/test_suite.erl",
     "templates/the_app.erl",
     "test/helper.rb",
     "test/test_mkerl.rb"
  ]
  s.homepage = %q{http://github.com/auser/mkerl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A template to start erlang projects.}
  s.test_files = [
    "test/helper.rb",
     "test/test_mkerl.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

